[build]
  base = "frontend"
  publish = "build"
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"
  NPM_FLAGS = "--legacy-peer-deps"
